name: Deploy Azure Functions with Code Scanning

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write  # Added for code scanning

env:
  PYTHON_VERSION: '3.11'
  DEPLOYMENT_BRANCH: 'develop'

jobs:
  code-scan:
    name: Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety flake8

      - name: Security scan with Bandit
        run: |
          bandit -r ./src -f sarif -o bandit-results.sarif || true
        continue-on-error: true

      - name: Dependency vulnerability scan with Safety
        run: |
          safety check --full-report || true
        continue-on-error: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:python"

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.sarif
        continue-on-error: true

  deploy:
    name: Deploy Azure Function
    needs: code-scan  # Wait for code scanning to complete before deploying
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - function_name: "uat1-deleteapi"
            path: "src/delete-api"
            tag_identifier: "delete-api"
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Extract tag info
        id: tag-info
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          FUNCTION_ID=$(echo $TAG_NAME | cut -d'-' -f2-)
          echo "function_id=$FUNCTION_ID" >> $GITHUB_OUTPUT
          echo "Extracted tag name: $TAG_NAME"
          echo "Extracted function ID: $FUNCTION_ID"

      - name: Verify tag is on main branch
        run: |
          git fetch origin main
          if git branch -r --contains ${{ github.ref }} | grep -q "origin/develop"; then
            echo "Tag is on main develop"
          else
            echo "Tag must be on the develop branch"
            exit 1
          fi

      - name: Setup Python
        if: matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        if: matrix.tag_identifier == steps.tag-info.outputs.function_id
        run: |
          if [ -f "${{ matrix.path }}/requirements.txt" ]; then
            pip install -r ${{ matrix.path }}/requirements.txt
          fi

      - name: Login to Azure
        if: matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Function
        if: matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: azure/functions-action@v1
        with:
          app-name: ${{ matrix.function_name }}
          package: ${{ matrix.path }}