name: Deploy Azure Functions

on:
  push:
    tags:
      - 'v*-*'  # matches v1.0.0-html-json, v1.0.0-json-to-index, etc.
    branches:
      - main  # Add this if you want to ensure tags are only from main branch
  workflow_dispatch:  # Keeps manual trigger option

env:
  PYTHON_VERSION: '3.11'
  DEPLOYMENT_BRANCH: 'main'  # Specify which branch to deploy from

jobs:
  deploy:
    name: Deploy Azure Function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - function_name: "testt-html-search-api"
            path: "azure-html-search"
            tag_identifier: "azure-html-search"
          - function_name: "testt-pdf-search-api"
            path: "azure-pdf-search"
            tag_identifier: "azure-pdf-search"
          - function_name: "testt-semantic-search-api"
            path: "semantic-search"
            tag_identifier: "semantic-search"
          - function_name: "html-tojson"
            path: "html-json"
            tag_identifier: "html-json"
          - function_name: "html-to-index"
            path: "json-to-index"
            tag_identifier: "json-to-index"
          - function_name: "pdf-indexer-function"
            path: "pdf-indexer-function"
            tag_identifier: "pdf-indexer-function"
          - function_name: "delete-api"
            path: "delete-api"
            tag_identifier: "delete-api"

    steps:
      - name: Extract tag info
        if: startsWith(github.ref, 'refs/tags/')
        id: tag-info
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          FUNCTION_ID=$(echo $TAG_NAME | cut -d'-' -f2-)
          echo "function_id=$FUNCTION_ID" >> $GITHUB_OUTPUT
          echo "Extracted function ID: $FUNCTION_ID from tag: $TAG_NAME"

      - name: Checkout repository
        if: github.event_name == 'workflow_dispatch' || matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOYMENT_BRANCH }}  # Always checkout the main branch
          fetch-depth: 0  # Fetch all history for tags

      - name: Verify tag is on main branch
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Check if the tag is on the main branch
          if ! git merge-base --is-ancestor ${{ github.sha }} origin/main; then
            echo "Error: Tag must be on the main branch"
            exit 1
          fi

      - name: Setup Python
        if: github.event_name == 'workflow_dispatch' || matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        if: github.event_name == 'workflow_dispatch' || matrix.tag_identifier == steps.tag-info.outputs.function_id
        run: |
          if [ -f "${{ matrix.path }}/requirements.txt" ]; then
            pip install -r ${{ matrix.path }}/requirements.txt
          fi

      - name: Login to Azure
        if: github.event_name == 'workflow_dispatch' || matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function
        if: github.event_name == 'workflow_dispatch' || matrix.tag_identifier == steps.tag-info.outputs.function_id
        uses: azure/functions-action@v1
        with:
          app-name: ${{ matrix.function_name }}
          package: ${{ matrix.path }}
